GET http://localhost:3000/api/password

###


GET http://localhost:3000/api/password/1

###


POST http://localhost:3000/api/password
Content-Type: application/json

{
  "name": "thread-password"
}

###

DELETE  http://localhost:3000/api/password/

###

PUT http://localhost:3000/api/password/1
Content-Type: application/json

{
  "name": "thread-password",
  "password": "strongpassword123"
}
###

PUT  http://localhost:3000/api/password/1/shuffle

###