GET http://localhost:3000/api/password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6IlRlc3QgTmFtZSIsImVtYWlsIjoidGVzdDRAZXhhbXBsZS5jb20iLCJpYXQiOjE3ODI5MjgyNDAsImV4cCI6MTc4MjkyOTE0MH0.AIpdY8y-SMbfMqsRU72_ood7veBfRN1qkcSXEMWhQXo

###


GET http://localhost:3000/api/password/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6IlRlc3QgZml2ZSIsImVtYWlsIjoidGVzdDVAZXhhbXBsZS5jb20iLCJpYXQiOjE3ODI5Mjg1NTYsImV4cCI6MTc4MjkyOTQ1Nn0.smWiOip7TbGgGwlAtzb1hL7Lqn8jqcjUbyjB1NEl9pk

###


POST http://localhost:3000/api/password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6IlRlc3QgZml2ZSIsImVtYWlsIjoidGVzdDVAZXhhbXBsZS5jb20iLCJpYXQiOjE3ODI5Mjg1NTYsImV4cCI6MTc4MjkyOTQ1Nn0.smWiOip7TbGgGwlAtzb1hL7Lqn8jqcjUbyjB1NEl9pk
Content-Type: application/json

{
  "name": "thread-password"
}

###

DELETE  http://localhost:3000/api/password/1
 
###

PUT http://localhost:3000/api/password/1
Content-Type: application/json

{
  "name": "thread-password",
  "password": "strongpassword123"
}
###

PUT  http://localhost:3000/api/password/1/shuffle
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6IlRlc3QgTmFtZSIsImVtYWlsIjoidGVzdDRAZXhhbXBsZS5jb20iLCJpYXQiOjE3ODI5Mjg1ODQsImV4cCI6MTc4MjkyOTQ4NH0.eDUdZpZmvUTsEoov43yZOpuAGvDtNyOKhqgfCB3SjV0
###


POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Test Name",
  "email": "test4@example.com"
}
###


POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "password": "Test@123",
  "email": "test4@example.com"
}
###


POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Test five",
  "password": "Test@123",
  "email": "test5@example.com"
}
###









