GET http://localhost:3000/api/password

###


GET http://localhost:3000/api/password/3

###


POST http://localhost:3000/api/password
Content-Type: application/json

{
  "name": "thread-password"
}

###

DELETE  http://localhost:3000/api/password/3

###

PUT http://localhost:3000/api/password/3

###