-- CREATE DATABASE
CREATE DATABASE PassWordManager;

-- CREATE PASSWORD TABLE
CREATE TABLE Passwords(
  PasswordID SERIAL PRIMARY KEY,
  PasswordName VARCHAR(200) NOT NULL,
  Password VARCHAR(100) NOT NULL,
  DateCreated TIMESTAMPZ DEFAULT CURRENT_TIMESTAMP
);