-- CREATE DATABASE
CREATE DATABASE PassWordManager;

-- CREATE USER TABLE
CREATE TABLE Users(
  UserID SERIAL PRIMARY KEY,
  UserName VARCHAR(150) NOT NULL,
  Email VARCHAR(200) NOT NULL UNIQUE,
  PasswordHash TEXT NOT NULL,
  DateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CREATE PASSWORD TABLE
CREATE TABLE Passwords(
  PasswordID SERIAL PRIMARY KEY,
  PasswordName VARCHAR(200) NOT NULL,
  Password VARCHAR(100) NOT NULL,
  UserID INT REFERENCES Users(UserID) ON DELETE CASCADE,
  DateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ALTER PASSWORD TABLE AND ADD USER ID COLUMN